### ISSUE TITLE
WARNING: field is not a valid property for field. 

### ISSUE THREAD

**Issue by AtallahFatma** [chargebee/chargebee-js-wrappers#103]
Hello,

I'm using the Chargebee JS React Wrapper. When loading fields I'm getting the following warning:

WARNING: field is not a valid property for field. 

If I remove the components of the card `CardComponent`, `CardNumber`, `CardExpiry`, `CardCVV` , warning disappear. 
Any ideas that might be causing the error?

![Screenshot 2022-11-15 at 5 37 23 PM](https://user-images.githubusercontent.com/26638076/201975618-b6c80004-efda-45c5-8035-5609871418d7.png)

Thanks in advance.

**Comment by takusen** [comment]
Hi, 

Facing the same issue here, any information about this (reason, and possibly way for fixing it)?

**Comment by adrianmxb** [comment]
Same issue here, are there already some more details what could cause this?

**Comment by unlayerbrian** [comment]
I'm seeing the same thing in our implementation of Chargebee.  It doesn't appear to have any negative effects, but I don't like to see console logs when entering payment information.

**Comment by vladimirvrabel** [comment]
I agree with all above. I've been following the tutorial (https://www.chargebee.com/checkout-portal-docs/components-fields-integrations.html#integrating-components) , but it's still displaying warning(s) for the card component in the Default/Fields mode.

**Comment by damyco** [comment]
Same issue when trying to use it with latest Next.js app.

**Comment by cb-dinesh** [comment]
This issue has been resolved.
