### ISSUE TITLE
Need support for Angular 16 & 17

### ISSUE THREAD

**Issue by edthompson-nf** [chargebee/chargebee-js-wrappers#151]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @chargebee/chargebee-js-angular-wrapper@2.0.0
npm ERR! Found: @angular/common@16.2.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.2.12" from the root project
npm ERR!   peer @angular/common@"^16.0.0 || ^17.0.0" from @angular/cdk@16.2.12
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^16.2.12" from the root project
npm ERR!     peer @angular/cdk@"16.2.12" from @angular/material@16.2.12
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^16.2.12" from the root project
npm ERR!       1 more (ziti-console-lib)
npm ERR!     3 more (@swimlane/ngx-charts, @swimlane/ngx-graph, ziti-console-lib)
npm ERR!   26 more (@angular/forms, @angular/material, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
**npm ERR! peer @angular/common@"^15.2.9" from @chargebee/chargebee-js-angular-wrapper@2.0.0**
npm ERR! node_modules/@chargebee/chargebee-js-angular-wrapper
npm ERR!   @chargebee/chargebee-js-angular-wrapper@"^2.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@15.2.10
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^15.2.9" from @chargebee/chargebee-js-angular-wrapper@2.0.0
npm ERR!   node_modules/@chargebee/chargebee-js-angular-wrapper
npm ERR!     @chargebee/chargebee-js-angular-wrapper@"^2.0.0" from the root project

**Comment by thehaseebahmed** [comment]
Are there any updates on this?

**Comment by TobyBladen** [comment]
Please could we have an update on this? Angular 15 security support ends next month, so it is important from a security standpoint that we get Angular 16 support soon as a bare minimum: https://endoflife.date/angular

**Comment by cb-dinesh** [comment]
Hi @TobyBladen , we are working on providing support for both Angular 16 and 17. 
Will update this thread once its released.

**Comment by cb-vaibhavpandey** [comment]
Angular v16 support is added in version - 3.0.0 
PR: #156

**Comment by TobyBladen** [comment]
> Angular v16 support is added in version - 3.0.0 PR: #156

Thank you, that's much appreciated. Please can I also confirm that Angular v17 for Chargebee will also be added ahead of November 2024, which is when Angular 16 security support will end? https://endoflife.date/angular

**Comment by cb-vaibhavpandey** [comment]
Sure, we will notify you as soon as this version update is available.

**Comment by cb-vaibhavpandey** [comment]
Angular v17 support is added in version 4.0.0
PR: #159
