### ISSUE TITLE
Uncaught NO_CONTAINER_ELEMENT: Container element not specified for card component

### ISSUE THREAD

**Issue by adamrisser** [chargebee/chargebee-js-wrappers#28]
Hello - 

For the life of me, I cannot get the JS wrappers to work. I cut and pasted all 3 examples into my NextJS project, init Chargee, then receive the following warning and error.

```
react-dom.development.js:88 Warning: Prop `id` did not match. Server: "card-field-3b3d13c5-bb9d-46c3-b696-b04aa9a5b885" Client: "card-field-e5e3da21-c40e-429a-9cc5-91f645dabc9e"
    in div (created by ChargebeeComponents)
    in ChargebeeComponents (created by ForwardRef)
    in ForwardRef (at billing/index.js:189)
    in div (at billing/index.js:175)
...
```

```
card-component.ts:219 Uncaught NO_CONTAINER_ELEMENT: Container element not specified for card component
    at J.value (https://js.chargebee.com/v2/7-948d33c5246d36af85a9.js:1:20376)
    at J.value (https://js.chargebee.com/v2/7-948d33c5246d36af85a9.js:1:22350)
    at ChargebeeComponents.componentDidUpdate (webpack-internal:///./node_modules/@chargebee/chargebee-js-react-wrapper/dist/chargebee-js-react-wrapper.esm.js:370:21)
    at commitLifeCycles (http://localhost:3000/_next/static/development/dll/dll_49dc72f77c9be8a30d1a.js?ts=1602088360094:20087:22)
    at commitLayoutEffects (http://localhost:3000/_next/static/development/dll/dll_49dc72f77c9be8a30d1a.js?ts=1602088360094:23055:7)
...
```

If I comment out my `<CardComponent />`, everything loads. Adding back into the example code then rethrows the errors/warnings.  Hopefully its something simple?

**Comment by cb-jose** [comment]
Hi Adam, we do not support Server side rendering at the moment. We have raised this as a feature request for the same.  Will provide you with an ETA soon.

**Comment by adamrisser** [comment]
Great thanks for the update.  For me, for the ETA, would love to know if we're talking Q4 or next year. Thanks again!

**Comment by cb-jose** [comment]
We are looking at mid Q4.

**Comment by dayvista** [comment]
@cb-jose any progress on this? Currently working with Next.js and trying to implement Chargebee.

**Comment by cb-jose** [comment]
Unfortunately, this got delayed due to some other priorities that came up last minute. We are looking at completing this quarter. Apologies on the delay.

**Comment by dayvista** [comment]
Thanks for the update! I was able to at least get the on-page checkout/self-serve portal working in the meantime, so Chargebee will still work for my project

**Comment by magicspon** [comment]
@cb-jose Any updates? 

I'm seeing a world of errors in nextjs.

![image](https://user-images.githubusercontent.com/3268717/113184394-06411e00-924d-11eb-9444-0d1a71d1ff05.png)

**Comment by magicspon** [comment]
Sorted... only rendering the components once the script has loaded.

```javascript
export default function Sub() {
	const cardRef = React.useRef()
	const onSubmit = (e) => {
		if (e) e.preventDefault()
		cardRef.current.tokenize().then((data) => {
			console.log("chargebee token", data.token)
		})
	}
	const [loaded, setLoaded] = React.useState(false)

	React.useEffect(() => {
		if (typeof window !== "undefined" && !loaded) {
			const chargebee = window.Chargebee.init({
				site: "oomphspring-test",
				publishableKey: "test_EYIYpb7Fomf6EoJSmPKAD65yjXgJQx6u",
			})
			if (chargebee) setLoaded(true)
		}
	}, [loaded])

	return (
		<>
			<Head>
				<script src="https://js.chargebee.com/v2/chargebee.js" />
			</Head>
			<div className="py-64">
				{loaded && (
					<form onSubmit={onSubmit}>
						<CardComponent ref={cardRef} />
						<button type="submit">Submit</button>
					</form>
				)}
			</div>
		</>
	)
}
```

**Comment by mwalden2004** [comment]
It's disappointing they've done nothing about this.

**Comment by cb-abhishek** [comment]
We have updated our code + documentation for NextJS Framework. 
Please refer: https://github.com/chargebee/chargebee-js-wrappers/tree/master/chargebee-js-react#server-side-rendering-using-nextjs
