### ISSUE TITLE
Add aria labels for react-wrapper

### ISSUE THREAD

**Issue by apennell** [chargebee/chargebee-js-wrappers#31]
## Problem

Currently the react-wrapper doesn't allow for accessible inputs. I have the following two issues called out by Axe:
- [Form elements must have labels](https://dequeuniversity.com/rules/axe/4.0/label?application=AxeChrome) ("critical" issue)
- [Frames must have title attribute](https://dequeuniversity.com/rules/axe/4.0/frame-title?application=AxeChrome) ("serious" issue)

 The following screenshots of the Axe issues are from the [live demo](https://www.recur.in/components-examples/react/#/example1) because they're also happening there:
<img width="565" alt="Screen Shot 2020-11-25 at 3 34 57 PM" src="https://user-images.githubusercontent.com/11039888/100291948-fed2d680-2f33-11eb-85bc-9fff2fca483f.png">
<img width="563" alt="Screen Shot 2020-11-25 at 3 35 07 PM" src="https://user-images.githubusercontent.com/11039888/100291951-00040380-2f34-11eb-9f47-53f22913dce3.png">

## Proposed Solution

The wrapper could accept a `label` attribute, and use that internally to set `aria-label` on the iframes and inputs.

**Comment by apennell** [comment]
@cb-jose I would argue that it's not an enhancement. This form isn't really useable for users that rely on screenreader technology.

**Comment by apennell** [comment]
@cb-dinesh @cb-jose Is there any update on when this might happen? It's a pretty easy fix, and extremely important. Without this, **Chargebee does not work**. Can I use Stripe instead, if there are no plans to make the Chargebee inputs work, or what is my alternative so that I can implement the CB service we are paying for in a way that is a11y compliant and all my users can use?

**Comment by cb-dinesh** [comment]
Hey @apennell We are planning for rolling out an update by end of next week. This should be addressed by then :) Will keep this thread posted.

**Comment by cb-dinesh** [comment]
Hi @apennell You should now be able to pass `ariaLabel` property just like how you'd pass placeholder. :) I am closing this thread. Please re-open if you still face any issues.
