### ISSUE TITLE
Can we have a separate method for validation?

### ISSUE THREAD

**Issue by SilverSting** [chargebee/chargebee-js-wrappers#4]
We'd like to validate the CardComponent (React wrapper) without necessarily generating a token.

Can you expose a `validate` function so that we can do something like this?

```
cardRef.current.validate((error) => {
  if (error) {
    // Do some error handling, such as setting the error message to a state.
    // eg. setErrorMessage(error.message)
  } else {
    // Continue with submission
  }
});
```

**Comment by cb-dinesh** [comment]
@Priya-dev / @SilverSting `validateCardDetails` method can be used to validate the card details https://www.chargebee.com/checkout-portal-docs/component-field-api-ref.html#validatecarddetails
