### ISSUE TITLE
React 17 incorrect peer dependency on install

### ISSUE THREAD

**Issue by SamuelLeclerc33** [chargebee/chargebee-js-wrappers#58]
The project seems to work fine with react 17, but a peer dependency flags an warning. Can this be fixed ? 

![image](https://user-images.githubusercontent.com/23220701/121815211-435d5f80-cc43-11eb-90d0-9c06dd94b551.png)

**Comment by christopherhill** [comment]
+1 Also experiencing this issue.

**Comment by dleunig** [comment]
Are there any chances to update on the newer version of react soon?

**Comment by gjj** [comment]
+1 any updates?

**Comment by cb-dinesh** [comment]
Hey, please install the latest version. Added react 17 to the peer dependencies.
