### ISSUE TITLE
Vue 3 compatibility 

### ISSUE THREAD

**Issue by shawnhooper** [chargebee/chargebee-js-wrappers#71]
The current Vue components are for Vue 2.   Would it be possible to get Vue 3 versions?

**Comment by TakeshiDaveau** [comment]
Hello,

Is there any work to make this lib compatible with Vue3 ?
I think it's important as it is the new default version fore Vue.

Thanks

**Comment by shawnhooper** [comment]
Any update on this issue?  Not having Vue 3 support is blocking me from fully upgrading our app, and will affect our SOC 2 audit.  May have to look at removing Chargebee from our app in the interim.

**Comment by cb-dinesh** [comment]
We are looking into this, will share an update at the earliest.

**Comment by JeremCafeyn** [comment]
@cb-dinesh, thanks for your reply, do you have an idea to when it will be available?

**Comment by cb-dinesh** [comment]
@JeremCafeyn You can expect this to roll out before June 24th.

**Comment by mcelligottnick** [comment]
@cb-dinesh Any movement on this?

**Comment by mcelligottnick** [comment]
@cb-dinesh  are we able to get an ETA?

**Comment by cb-dinesh** [comment]
Hey @mcelligottnick, Sorry this got a bit delayed. I will be wrapping this by end of this week. Thank you for understanding.

Please follow #94

**Comment by cb-dinesh** [comment]
Hi, published a new version for vue wrapper. Please test it with vue3, and update this thread if you run into any issues.

**Comment by mcelligottnick** [comment]
Thanks mate! Will test in the coming days.

**Comment by mcelligottnick** [comment]
@cb-dinesh this is working for me now, thanks.
