### ISSUE TITLE
Custom Chargebee form integration results in Unauthorized error

### ISSUE THREAD

**Issue by bahdcoder** [chargebee/chargebee-js-wrappers#74]
Hello. Using the react wrapper, I created a custom form integration. I can confirm that I correctly initialised Chargebee, and also correctly passed the chargebee instance into the provider.

I can also confirm that the API key and site are correct. 

I get the following error when trying to load the page.

<img width="1440" alt="Screenshot 2022-01-26 at 01 38 34" src="https://user-images.githubusercontent.com/19477966/151083360-0a40692a-5343-4f97-863d-e3da43d1fac1.png">

Due to this error I cannot tokenize the card and proceed with creating a subscription. 

Any help would be greatly appreciated. Thank you very much.

**Comment by cb-samuel** [comment]
@bahdcoder 

Hello Kati, hope you are doing well :). This is Samuel from Chargebee Technical Team.

With reference to the query you have raised above, I can see that you are using Chargebee's React Wrapper flavor of Hosted Components and Fields. So when you initialize your Chargebee site instance, please ensure that you are using your Chargebee site's Publishable API key and not a full access API key.

For more insights please refer to this [link](https://www.chargebee.com/checkout-portal-docs/components-fields-integrations.html#%E2%80%8B%E2%80%8Binitializing-a-chargebee-instance)

If you need more assistance in setting this up please feel free to reply to this thread or write to support@chargebee.com.

Hope i have clarified your query 😃 

Have a nice day ahead !

**Comment by bahdcoder** [comment]
Hey @cb-samuel . Thank you for your help. Yes that helped out a lot.

**Comment by bahdcoder** [comment]
Hey @cb-samuel. 

Quick one if you could still help out. 

Do you have any guide on creating subscriptions for users using custom forms? All the ones I've found end with generating the token.

Would be awesome to get a link. 

Thanks very much !

**Comment by cb-samuel** [comment]
Hey @bahdcoder Apologies for the delay in response. [Here](https://www.chargebee.com/checkout-portal-docs/components-fields.html#workflow) is the reference for your query. You can write to support@chargebee.com for detail insights.
