### ISSUE TITLE
@chargebee/chargebee-js-react-wrapper not working with react@18 yet

### ISSUE THREAD

**Issue by welearndan** [chargebee/chargebee-js-wrappers#85]
When updating to the newest react version and running ```npm i``` with ```@chargebee/chargebee-js-react-wrapper@0.4.3```, the following error is thrown:

```npm ERR! While resolving: @chargebee/chargebee-js-react-wrapper@0.4.3 npm ERR! Found: react@18.0.0```

I think this can be fixed by updating the version number in peer-dependencies to 18 as well

**Comment by JasonNoonan** [comment]
The lack of chargebee's wrapper supporting this is preventing our entire app from updating our stack. Please, add support for this soon.

**Comment by cb-dinesh** [comment]
We are looking into this. Will share an update at the earliest.

**Comment by mwalden2004** [comment]
This is affecting us as well, please let us know when this is changed as it is really holding us back.

**Comment by cb-dinesh** [comment]
@mwalden2004 You can expect react 18 support to be available by June 24th.

**Comment by impaler** [comment]
Seems to be working great, only issue I saw was with StrictMode enabled see https://github.com/chargebee/chargebee-js-wrappers/issues/98
