### ISSUE TITLE
Publish Angular Ivy distribution

### ISSUE THREAD

**Issue by Nightapes** [chargebee/chargebee-js-wrappers#87]
When installing `@chargebee/chargebee-js-angular-wrapper` with the latests Angular we got following warning:

```
Processing legacy "View Engine" libraries:
- @chargebee/chargebee-js-angular-wrapper [es2015/esm2015] (git+https://github.com/chargebee/chargebee-js-wrappers.git)
- @chargebee/chargebee-js-angular-wrapper [main/umd] (git+https://github.com/chargebee/chargebee-js-wrappers.git)
Encourage the library authors to publish an Ivy distribution.
```

Would it be possible to publish a Angular Ivy Version?

**Comment by ryanvall** [comment]
+1, this is interfering with our Angular 13 upgrade. @cb-dinesh can this be implemented?

**Comment by cb-farhanh** [comment]
Support for Angular 14 has been released.
Closing this thread. Please start a new github issue if there are any open bugs.
