### ISSUE TITLE
Any plans for a normal npm package of chargebee?

### ISSUE THREAD

**Issue by mhombach** [chargebee/chargebee-js-wrappers#99]
Our company just decided to use Chargebee and I'm mindblown that there seems to not be any normal npm package of the lib existing for the frontend? Even this wrapper here seems to rely on the src-file be loaded from the html, then to be inited at the correct point in time etc.... Why is there no standard package so we can just bundle the Chargebee lib to our app the normal way?

Please respond asap, that not-existing package and the mostly unmaintained repository here are huge red flags for us.

**Comment by MadaShindeInai** [comment]
@mhombach  FYI. This libs are solutions for cases when you need to collect and pre-process user data 'in app'. I spent some hours implementing this solution to understand that CardComponent - it is form for data collection. 😫 
If you want to collect user data on chargebee side, and just implement Drop-In solution - you don't need this lib.
But yes, you need to do this embedding script. According their responce speed i do not think this package will be done / done fast, but having no npm package is not red flag. Lack of implementation examples + outdated suggested solutions - can be.

**Comment by mhombach** [comment]
@MadaShindeInai thanks for the reply. I now looked into it in more detail and understand now the idea of those "wrappers", and this is not what we intend to use. Although you can obviously make your app work without a NPM package, there are sometimes good reasons why you want to bundle the code and not load it async from some 3rd party server.
